[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Configure the stepper motor pins and speed here
build_flags = \
  -D STEPPER_PIN_1=21 \
  -D STEPPER_PIN_2=22 \
  -D STEPPER_PIN_3=19 \
  -D STEPPER_PIN_4=18
